


export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS'
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED'
export const FETCH_TASKS_START = 'FETCH_TASKS_START'
export const TASK_INIT = 'TASK_INIT'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAILED = 'CREATE_TASK_FAILED'
export const CREATE_TASK_START = 'CREATE_TASK_START'
export const FETCH_PICKED_TASK_SUCCESS = 'FETCH_PICKED_TASK_SUCCESS'
export const CLEAR_TASK = 'CLEAR_TASK'
export const CHANGE_VIEW = 'CHANGE_VIEW'